language: csharp
solution: AWSTestTravis.sln
install: false
script:
  - echo "No compile please"
deploy:
  before_deploy:
    - mkdir /tmp/deployment
    - cp .deployment/*.xml /tmp/deployment/.
    - rm -rf .deployment 
    - mkdir -p /tmp/deployment/Content/C_C/Users/kevin/source/repos/AWSTestTravis/AWSTestTravis/obj/Debug/Package/PackageTmp
    - cp -R * /tmp/deployment/Content/C_C/Users/kevin/source/repos/AWSTestTravis/AWSTestTravis/obj/Debug/Package/PackageTmp/.
    - rm -rf * 
    - cp -R /tmp/deployment/* .
  provider: elasticbeanstalk
  access_key_id: AKIAJJ6JOCBCVK4GGSEA
  secret_access_key:
    secure: NfGer/MUYrAJGURCsjNwv2butCyDOyd5Pf3SxKbbWH/AxXUm/LC6dG64Bomw5F6NMnxkqkerMz/kaPutvAv2nFcquorr4Ac6k+3LRbzkLJH9DBTfaZZMrzmPEedw7Ayf28TKpjj4W+oFpSkfg8KKaUn8yZitfHUPWeCCVyJb0nKngr1KgPsKplDt3vTGzLv2cz/+TTDbH4NBeSzqDDrahQOeDYJR2Rv0yj7ChN25hICgWDxEYvzB9Rb4nhd2+agmR9e8LwB4dkOCAY8v2Ex+fFTqDj3s0sVaGPNi9+klg9xeAozEJEyY0UgUWlpDyUZJDQG9hk2feoBDXZIi6qenGkj2Z8jQK5DyFgWHerYBI4kna+8XFZYStDSHTOnam/N7Ipebh1UgSqKbQOcwFCy3H6w3wyEt27bCh9sk4ny/1C60yRE+0wKhE0KcJGzjWzdYVxEOpK3xeg6UqHbWT++mxASukZst9l212Vke1/9WrRTy8PvGMdGzQS/BPR9e1J+BhidtadI4zoLDDb6oVfcqBsD4fATvIOckwwVoVBJMxWbRk0YidlFNGwK9BGS7qDR6AqHDFZA1WBbjL/+Ws4xtQMGPwY9yOO3ikn/9h3TAjtLgAaAFvPdp1D1HE4u/aMmiHmXi8vyqoPbYq0zt5SMEMAO8FX4ohVDGduLuLIO8wUM=
  region: eu-west-1
  app: Spokd Website - Development
  env: Development
  on:
    repo: kevin-coyle/awsasptravistest
  bucket_name: drutek-deployments
